# Header
navname: Ugly Garden

# navigatior items
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag
  About: /about
  Friends: /friends

# favicon
favicon: /hollow.ico

# Profile
nickname: Baileys Wu

### this variable is MarkDown form.
description: 拙技园
avatar: /13285397.png

# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
links:
  Blog: https://www.douban.com/people/Baileyswu/
  # Category: /category
  Tags: /tag
  # Link:
  # Resume:
  # Publish:
  # Trophy:
  # Gallery:
  # RSS:
  # AliPay:
  # ZhiHu: 
  # LinkedIn:
  # FaceBook:
  # Twitter:
  # Skype:
  # CodeSandBox:
  # CodePen:
  # Sketch:
  # Gitlab:
  # Dribbble:
  # Instagram:
  # Reddit:
  # YouTube:
  # QQ:
  Weibo: http://weibo.com/Danliwoo
  # WeChat:
  Github: https://github.com/Baileyswu

# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# Post page
## Post_meta
post_meta_enable: true

post_author_enable: true
post_date_enable: true
post_category_enable: true
## Post copyright
post_copyright_enable: false

post_copyright_author_enable: true
post_copyright_permalink_enable: true
post_copyright_license_enable: true
post_copyright_license_text: Copyright (c) 2019 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> LICENSE
post_copyright_slogan_enable: true
post_copyright_slogan_text: Do you believe in <strong>DESTINY</strong>?
## toc
post_toc_enable: true

# Page
page_title_enable: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MM/DD, YYYY
time_format: H:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot


# plugin functions
## Mathjax: Math Formula Support
## https://www.mathjax.org
mathjax:
  enable: true
  import: global # global or demand
  ## global: all pages will load mathjax,this will degrade performance and some grammers may be parsed wrong.
  ## demand: Recommend option,if your post need fomula, you can declare 'mathjax: true' in Front-matter
  # Use 2.7.1 as default, jsdelivr as default CDN, works everywhere even in China
  # cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  # For newMathJax CDN (cdnjs.cloudflare.com) with fallback to oldMathJax (cdn.mathjax.org).
  # cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  # For direct link to MathJax.js with CloudFlare CDN (cdnjs.cloudflare.com).
  # cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML
  # For automatic detect latest version link to MathJax.js and get from Bootcss.
  # cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

gitalk:
  enable: true
  ClientID: 7ac4af6b2ef79db6191b #Client ID,填入上一步获取的ID
  ClientSecret: b5cf578803e18f2c9c3203761db3988e9073361d #Client Secret，填入上一步获取的ID
  repo: Baileyswu.github.io #你要存放的项目名,如果博客部署在github可以放一起
  owner: Baileyswu #这个项目名的拥有者（GitHub账号或组织）
  adminUser: ['Baileyswu'] #管理员用户
  ID: location.pathname #页面ID
  labels: ['comments'] #GitHub issues的标签
  perPage: 15 #每页多少个评论
  pagerDirection: first #排序方式是从旧到新（first），还是从新到旧（last）
  createIssueManually: true #是否自动创建isssue，自动创建需要当前登录的用户为adminuser
  distractionFreeMode: false #是否启用快捷键(cmd|ctrl + enter) 提交评论
  
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  comment: false
  views: true
  appId: 0Fj98eQg9XCdRJPI2p1yxYCN-gzGzoHsz #your leancloud appId
  appKey: Qsrhj224GhWhBgFDfnfmuRCD #your leancloud appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: Listen to Me # valine comment input placeholder(like: Please leave your footprints )
  avatar: https://avatars3.githubusercontent.com/u/13285397?s=460&v=4 # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  lang: zh-cn

friends:
  - name: 燕燕姐
    href: https://shengrang.github.io/
    avatar: http://shengrang.github.io/mogu.gif
  - name: 俊俊oba
    href: https://jiajungong.github.io
    avatar: https://jiajungong.github.io/images/profile.JPG
  - name: 小白
    href: https://miniminiwhite.github.io/
    avatar: https://miniminiwhite.github.io/images/edwin_avatar.jpg
  - name: 海哥
    href: https://blog.csdn.net/whai362
    avatar: https://profile.csdnimg.cn/C/1/E/3_whai362
    class: avatar_pic
  - name: 小明
    href: https://zongdaoming.github.io/
    avatar: https://avatars1.githubusercontent.com/u/25998183?s=460&u=b5d3957a3b4f272ad861c8bd4009b8391ea7cac4&v=4
  - name: 鸟叔
    href: https://blog.csdn.net/mrbird_to_fly
    avatar: https://profile.csdnimg.cn/A/5/B/3_mrbird_to_fly
    class: avatar_pic
  - name: yezi
    href: https://www.soleaf.xyz/
    avatar: http://www.soleaf.xyz/wp-content/uploads/2020/04/诺瓦露.jpg
  # - name: shakex
  #   href: https://shakex.github.io/
  #   avatar: https://github.com/shakex/shakex.github.io/blob/master/images/kai.png